### ISSUE TITLE
Issuse

### ISSUE THREAD

**Issue by longago2009** [stephanfr/Cork#2]
Hello，Stephan 
Thank for your shared code.
Cork is very useful for my work.
I found one issue.
Sometime when i use Intersection method to two 3d models,
but i get Difference method result.

I used to use vtk , qCork, sgCore  boolean operation
encountered the same problem.
 Maybe I was using a 3D model too special
![cork](https://user-images.githubusercontent.com/21105296/39990005-1c77f046-579e-11e8-8307-00e2ab541cb0.jpg)

**Comment by stephanfr** [comment]
If you are having the same problem using multiple different packages then I don't think this is a problem with Cork.  I would check your models, perhaps the normals on the second model.  If they are flipped, you might get this kind of result.

Good Luck,

Stephan
